### ISSUE TITLE
Level1 코드 리뷰입니다.

### ISSUE THREAD

**Issue by klettermi** [YiHwanRyu/spring-practice-level1#1]
RESTful하게 잘 구현하신 것 같습니다!!
BlogService가 게시물에 관련된 서비스라서 PostService로 명명하면 더 좋을 것 같습니다!
createPost 사용 시 빈 값이 들어가도 값이 들어가는 것에 대해 예외처리를 하면 좋을 것 같습니다!

**Comment by zzangoobrother** [comment]
전체적으로 잘 하셨습니다.
두가지만 말씀드리면
먼저 BlogService 메소드에 if else 문이 많습니다. 되도록이면 if 문만 사용하도록 하시고, 왜 if 문만 사용하다록 권장하는지 찾아보시면 좋습니다.
두번째로 @Transactional 을 update 메소드에서만 사용하셨는데 @Transactional 을 어떻게 사용해야 좋은지 보시면 좋겠습니다.
@Transactional 와 @Transactional(readOnly = true) 가 무엇인지 보시면 좋습니다.

전체적으로 깔끔하게 잘 하였습니다. 다음 레벨에서도 화이팅 하세요!!!
